version: '3.8'
name: Ketu_v1
services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_POSTGRES_HOST=postgres
      - APP_POSTGRES_PORT=5430
      - APP_POSTGRES_USERNAME=postgres
      - APP_POSTGRES_PASSWORD=postgres
      - APP_POSTGRES_DBNAME=myapp
      - APP_POSTGRES_SSLMODE=disable
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    command: -p 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: