version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_POSTGRES_HOST=postgres
      - APP_POSTGRES_PORT=5430  # Match PostgreSQL's port
      - APP_POSTGRES_USERNAME=postgres
      - APP_POSTGRES_PASSWORD=postgres
      - APP_POSTGRES_DBNAME=myapp
      - APP_POSTGRES_SSLMODE=disable
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    command: -p 5430  # Set PostgreSQL to listen on port 5430
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - "5430:5430"  # Map host port 5430 to container port 5430
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5430"]  # Update healthcheck port
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: