server:
  port: "8080"
  host: "localhost"
  readTimeout: "10s"
  writeTimeout: "10s"

postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "myapp"
  slide: "disable"

jwt:
  accessSecret: "superSecret"
  refreshSecret: "refreshSecret"
  accessTTL: "15m"
  refreshTTL: "720h"

logger:
  level: "debug"