server:
  port: "8090"
  host: "0.0.0.0"

postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "ke2"
  sslmode: "disable"

jwt:
  accessTTL: "15m"
  refreshTTL: "720h"

logger:
  level: "debug"
