postgres:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "myapp"
  sslmode: "disable"

server:
  port: "8090"
  host: "0.0.0.0"

jwt:
  accessSecret: "your-access-secret"
  refreshSecret: "your-refresh-secret"
  accessTTL: "15m"
  refreshTTL: "720h"