postgres:
  host: "postgres"  # Change this from "localhost" to "postgres"
  port: "5430"
  username: "postgres"
  password: "postgres"
  dbname: "myapp"
  sslmode: "disable"

server:
  port: "8090"
  host: "0.0.0.0"  # Change this to allow external connections

jwt:
  accessSecret: "your-access-secret"
  refreshSecret: "your-refresh-secret"
  accessTTL: "15m"
  refreshTTL: "720h"